### ISSUE TITLE
你好，用AS来跑您的程序时出现了如下错误  可以看一下吗

### ISSUE THREAD

**Issue by YUAN-YANG007** [hyyz3293/GarbageSorting#3]
What went wrong:
Execution failed for task ':app:validateSigningLeShopDebug'.
> Keystore file 'D:\Google\android_money\JackBarrage\jack.jks' not found for signing config 'debugConfig'.

**Comment by hyyz3293** [comment]
build.app  
里面 将下面注释掉 即可 -


     //签名
//    signingConfigs {
//        release {
//            storeFile file('D:/Google/android_money/JackBarrage/jack.jks')//签名文件
//            storePassword "123456"
//            keyAlias "keystore"
//            keyPassword "123456"  //签名密码
//        }
//        debugConfig {
//            keyAlias 'keystore'
//            keyPassword '123456'
//            storeFile file('D:/Google/android_money/JackBarrage/jack.jks')
//            storePassword '123456'
//        }
//    }
//
//    buildTypes {
//        release {
//            // 是否去除未利用的资源(必须和代码混淆同时开启)
//            shrinkResources true
//            // 是否开启代码混淆
//            minifyEnabled true
//            // 是否开启自动拆分多个Dex
//            multiDexEnabled true
//            //混淆文件
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.release
//        }
//        debug {
//            shrinkResources false
//            minifyEnabled false
//            multiDexEnabled true
//            //混淆文件
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
//            signingConfig signingConfigs.debugConfig
//        }
//    }

**Comment by YUAN-YANG007** [comment]
程序跑成功了，太感谢您了

**Comment by hyyz3293** [comment]
记得点赞

**Comment by YUAN-YANG007** [comment]
请问可以留下联系方式吗   我有些东西  希望可以请教您
