### ISSUE TITLE
你好，我用AS跑的时候报错了。请问你帮我看一下吗

### ISSUE THREAD

**Issue by OtisChan1** [hyyz3293/GarbageSorting#5]
signingConfigs {
        release {
            storeFile file('D:/Google/android_money/JackBarrage/jack.jks')//这里错误
            storePassword "123456"
            keyAlias "keystore"
            keyPassword "123456"
        }
        debugConfig {
            keyAlias 'keystore'
            keyPassword '123456'
            storeFile file('D:/Google/android_money/JackBarrage/jack.jks')//这里错误
            storePassword '123456'
        }
    }

**Comment by hyyz3293** [comment]
注销那一块代码即可
