### ISSUE TITLE
介绍该app

### ISSUE THREAD

**Issue by wulalah** [hyyz3293/GarbageSorting#6]
你好，请问有详细介绍这个APP的内容吗？有些地方不是很懂

**Comment by hyyz3293** [comment]
没有哟--代码看看就好了

**Comment by wulalah** [comment]
好的，谢谢博主回信，打扰博主啦！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月17日(周一) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hyyz3293/GarbageSorting] 介绍该app (#6)




 
没有哟--代码看看就好了
